[msg MyRoom_Text]
[f 0 5 -258][f 2 1]Quick interact[n][f 1 1][e]

[sel MyRoom]
[f 0 5 -258][f 2 1]Futon[e]
[f 0 5 -258][f 2 1]Desk[e]
[f 0 5 -258][f 2 1]TV[e]
[f 0 5 -258][f 2 1]Small desk[e]
[f 0 5 -258][f 2 1]Sofa[e]
[f 0 5 -258][f 2 1]Calendar[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg LivingRoom_Text]
[f 0 5 -258][f 2 1]Quick interact[n][f 1 1][e]

[sel LivingRoom]
[f 0 5 -258][f 2 1]Save point[e]
[f 0 5 -258][f 2 1]Fridge[e]
[f 0 5 -258][f 2 1]Farm[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg ShopNorth_Text]
[f 0 5 -258][f 2 1]Quick interact[n][f 1 1][e]

[sel ShopNorth]
[f 0 5 -258][f 2 1]Aiya Chinese Diner[e]
[f 0 5 -258][f 2 1]Bulletin board[e]
[f 0 5 -258][f 2 1]Cancel[e]
