[msg Welcome1]
[f 0 5 65278][f 2 1]You're free to explore the world around[n]you. You can set a sound beacon on[n]nearby things, and even auto-walk to them.[n][f 1 1][e]

[msg Welcome2]
[f 0 5 65278][f 2 1]Whenever you like, press F to open the[n]travel menu. It has more options[n]to help you on your journey.[n][f 1 1][e]

[msg RoomTip1]
[f 0 5 65278][f 2 1]In certain places, you can press Shift[n]and F, or Left Trigger plus X on a[n]controller, to open Quick Interact.[n][f 1 1][e]

[msg RoomTip2]
[f 0 5 65278][f 2 1]From it, choose a spot and you'll be[n]taken straight to it. Try it here:[n]your desk, the TV, and more.[n][f 1 1][e]

[msg RoomTip3]
[f 0 5 65278][f 2 1]You can also press F1, or hold both[n]triggers and press Start, to open the[n]Accessibility Settings and its Help.[n][f 1 1][e]

[msg DungeonTip1]
[f 0 5 65278][f 2 1]In dungeons, sound is your guide:[n]beacons for the stairs and chests, the[n]shadow radar, and the wall sounds.[n][f 1 1][e]

[msg DungeonTip2]
[f 0 5 65278][f 2 1]Explore freely until you find the[n]stairs. Then open the menu with F, X[n]on a controller, for the next floor.[n][f 1 1][e]

[msg DungeonTip3]
[f 0 5 65278][f 2 1]Learn more any time in the dungeon[n]tips, under Help in the Accessibility[n]Settings menu.[n][f 1 1][e]
